{
 "title": "OpenNARS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Version", "query": "stats_counts.Open-NARS.*" },
   {
    "name": "CrossingSessionID",
    "label": "CrossingSessionID",
    "query": "stats_counts.Open-NARS.$Version.*"
   },
   {
    "name": "PongSessionId",
    "query": "stats_counts.Open-NARS.$Version.*"
   }
  ]
 },
 "panels": [
  { "title": "Crossing Simulator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Matched Predictions vs Total Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPred), 'matchdPredictions')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPred), 'totalPredictions')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPred), 'matchdPredictions'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPred), 'totalPredictions')), 'ratio')"
    }
   ]
  },
  {
   "title": "Actual Confidence vs Predicted Confidence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPredConf), 'actualConf')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPredConf), 'PredictedConf')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPredConf), 'actualConf'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPredConf), 'PredictedConf')), 'ratio')"
    }
   ]
  },
  { "title": "Pong", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pong Hit & Miss Totals with Hit/Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'Ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')), 'Ratio')"
    }
   ]
  },
  {
   "title": "Pong Hit/Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(divideSeries(#B, #A), 'Ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'misses')), 'Ratio')"
    },
    {
     "target": "alias(aggregateLine(#D, 'average', 'Average'), 'Average')",
     "targetFull": "alias(aggregateLine(alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'misses')), 'Ratio'), 'average', 'Average'), 'Average')"
    }
   ]
  },
  {
   "title": "Pong Hit & Miss Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit')"
    },
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')"
    }
   ]
  },
  {
   "title": "Pong Miss-Distance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.Open-NARS.$Version.$PongSessionId.missDistance, 'Miss-Distance')"
    },
    {
     "target": "alias(movingAverage(stats.Open-NARS.$Version.$PongSessionId.missDistance, '5min'), 'Moving Average')"
    }
   ]
  },
  {
   "title": "Pong Misses",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Misses')"
    }
   ]
  },
  {
   "title": "Pong Hits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit)"
    }
   ]
  },
  {
   "title": "Pong Hit/Miss Ratio (Latest)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(#A, #B)",
     "targetFull": "divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Misses'))"
    }
   ]
  },
  {
   "title": "Pong Miss-Distance Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$PongSessionId.missDistance), 'Miss-Distance Total')"
    }
   ]
  }
 ]
}