{
 "title": "OpenNARS Dashboard",
 "time": { "from": "now-90m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Version", "query": "stats_counts.Open-NARS.*" },
   {
    "name": "CrossingSessionID",
    "label": "CrossingSessionID",
    "query": "stats_counts.Open-NARS.$Version.*"
   },
   {
    "name": "PongSessionId",
    "query": "stats_counts.Open-NARS.$Version.*"
   }
  ]
 },
 "panels": [
  { "title": "Crossing Simulator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction Volume by Temporal Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Accumulated predictions" }
   ],
   "targets": [
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPred), '< 50')"
    },
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm2Pred), '< 100')"
    },
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm3Pred), '< 200')"
    },
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm4Pred), '< 500')"
    },
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm5Pred), '< 1000')"
    },
    {
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPred), '>= 1000')"
    }
   ]
  },
  {
   "title": "Prediction Accuracy over Temporal Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Prediction Accuracy" }
   ],
   "targets": [
    {
     "refCount": 4,
     "target": "alias(divideSeries(#A, #B), '< 50 ratio')",
     "targetFull": "alias(divideSeries(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPred), integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTermPred)), '< 50 ratio')"
    },
    {
     "refCount": 4,
     "target": "alias(divideSeries(#D, #E), '< 100 ratio')",
     "targetFull": "alias(divideSeries(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm2Pred), integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTerm2Pred)), '< 100 ratio')"
    },
    {
     "refCount": 4,
     "target": "alias(divideSeries(#G, #H), '< 200 ratio')",
     "targetFull": "alias(divideSeries(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm3Pred), integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTerm3Pred)), '< 200 ratio')"
    },
    {
     "refCount": 4,
     "target": "alias(divideSeries(#J, #K), '< 500 ratio')",
     "targetFull": "alias(divideSeries(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm4Pred), integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTerm4Pred)), '< 500 ratio')"
    },
    {
     "refCount": 4,
     "target": "alias(divideSeries(#M, #N), '< 1000 ratio')",
     "targetFull": "alias(divideSeries(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTerm5Pred), integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTerm5Pred)), '< 1000 ratio')"
    }
   ]
  },
  {
   "title": "(Short Term < 50) Matched Predictions vs Total Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Accumulated Predictions" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPred), 'matchedShortTermPrediction')"
    },
    {
     "refCount": 1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTermPred), 'totalShortTermPredictions')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPred), 'matchedShortTermPrediction'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTermPred), 'totalShortTermPredictions')), 'ratio')"
    }
   ]
  },
  {
   "title": "(Short Term < 50) Actual Expectation vs Predicted Expectation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Accumulated Expectation" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPredConf), 'actualShortTermExpectation')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTermPredConf), 'PredictedSHortTermExpectation')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctShortTermPredConf), 'actualShortTermExpectation'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallShortTermPredConf), 'PredictedSHortTermExpectation')), 'ratio')"
    }
   ]
  },
  {
   "title": "(Long Term) Matched Predictions vs Total Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Accumulated Predictions" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPred), 'matchdPredictions')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPred), 'totalPredictions')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPred), 'matchdPredictions'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPred), 'totalPredictions')), 'ratio')"
    }
   ]
  },
  {
   "title": "(Long Term) Actual Expectation vs Predicted Expectation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Accumulated Expectation" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPredConf), 'actualExpectation')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPredConf), 'PredictedExpectation')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.correctPredConf), 'actualExpectation'), alias(integral(stats.Open-NARS.$Version.$CrossingSessionID.overallPredConf), 'PredictedExpectation')), 'ratio')"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pong Hit & Miss Totals with Hit/Miss Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit')"
      },
      {
       "refCount": -1,
       "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')"
      },
      {
       "target": "alias(divideSeries(#A, #B), 'Ratio')",
       "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')), 'Ratio')"
      }
     ]
    },
    {
     "title": "Pong Hit/Miss Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "alias(divideSeries(#B, #A), 'Ratio')",
       "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'misses')), 'Ratio')"
      },
      {
       "target": "alias(aggregateLine(#D, 'average', 'Average'), 'Average')",
       "targetFull": "alias(aggregateLine(alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'misses')), 'Ratio'), 'average', 'Average'), 'Average')"
      }
     ]
    },
    {
     "title": "Pong Hit & Miss Totals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hit')"
      },
      {
       "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Miss')"
      }
     ]
    },
    {
     "title": "Pong Miss-Distance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(stats.Open-NARS.$Version.$PongSessionId.missDistance, 'Miss-Distance')"
      },
      {
       "target": "alias(movingAverage(stats.Open-NARS.$Version.$PongSessionId.missDistance, '5min'), 'Moving Average')"
      }
     ]
    },
    {
     "title": "Pong Misses",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Misses')"
      }
     ]
    },
    {
     "title": "Pong Hits",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit)"
      }
     ]
    },
    {
     "title": "Pong Hit/Miss Ratio (Latest)",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.hit), 'Hits'), alias(integral(stats_counts.Open-NARS.$Version.$PongSessionId.miss), 'Misses'))"
      }
     ]
    },
    {
     "title": "Pong Miss-Distance Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "alias(integral(stats.Open-NARS.$Version.$PongSessionId.missDistance), 'Miss-Distance Total')"
      }
     ]
    }
   ]
  }
 ]
}