{
 "title": "Pong Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SessionID",
    "label": "SessionID",
    "query": "stats_counts.Open-NARS.v3_0_2.*"
   },
   { "name": "Version", "query": "stats_counts.Open-NARS.*" }
  ]
 },
 "panels": [
  {
   "title": "Pong Hit & Miss Totals with Hit/Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'Hit')"
    },
    {
     "refCount": -1,
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'Miss')"
    },
    {
     "target": "alias(divideSeries(#A, #B), 'Ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'Hit'), alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'Miss')), 'Ratio')"
    }
   ]
  },
  {
   "title": "Pong Hit/Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(divideSeries(#B, #A), 'Ratio')",
     "targetFull": "alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'misses')), 'Ratio')"
    },
    {
     "target": "alias(aggregateLine(#D, 'median', false), 'Average')",
     "targetFull": "alias(aggregateLine(alias(divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'hits'), alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'misses')), 'Ratio'), 'median', false), 'Average')"
    }
   ]
  },
  {
   "title": "Pong Hit & Miss Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'Hit')"
    },
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'Miss')"
    }
   ]
  },
  {
   "title": "Pong Miss-Distance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.Open-NARS.$Version.$SessionID.missDistance, 'Miss-Distance')"
    }
   ]
  },
  {
   "title": "Pong Misses",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'Misses')"
    }
   ]
  },
  {
   "title": "Pong Hits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'Misses')"
    }
   ]
  },
  {
   "title": "Pong Hit/Miss Ratio (Latest)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(#A, #B)",
     "targetFull": "divideSeries(alias(integral(stats_counts.Open-NARS.$Version.$SessionID.hit), 'Hits'), alias(integral(stats_counts.Open-NARS.$Version.$SessionID.miss), 'Misses'))"
    }
   ]
  },
  {
   "title": "Pong Miss-Distance Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(integral(stats.Open-NARS.$Version.$SessionID.missDistance), 'Miss-Distance Total')"
    }
   ]
  }
 ]
}